### PR TITLE
Handle 32-bit Python on 64-bit Windows

### PR DESCRIPTION
**Pull request by sikyu**
Also, reg path changed from WinVNC4 to vncserver. This will cover the following issue:
https://github.com/trinitronx/vncpasswd.py/issues/4

### CODE REVIEW

**Comment by trinitronx** [comment]
Nice work on fixing the 64bit / 32bit registry access issue.  Although it seems like this will break backwards compatibility with the old registry key `WinVNC4`?  It's been a while since I've used Windows or RealVNC, so I'm guessing that in some newer version of RealVNC they changed the registry key name to `vncserver`?

Not sure how to gracefully handle this if we want backwards compatibility other than to use `try` / `except` blocks to check for each one?  Otherwise, I suppose we can just release this as `2.0` and mark incompatibility with older RealVNC versions that use the `WinVNC4` key name.

**Comment by sikyu** [comment]
I was thinking about that but RealVNC has been releasing newer versions multiple times a year. It has to be really old version to use the old key. But I will add checking just in case.

**Comment by sikyu** [comment]
Kindly check, should now cover both cases.

**Comment by trinitronx** [comment]
@sikyu:  Thanks for making that change!  Looks great to me!

Yeah, I'm sure it's been quite a while since I needed this on Windows so they probably have made a lot of updates to RealVNC since then.  Anyway, thanks for the contribution!

**Pull request merged**
